### ISSUE TITLE
Design account creation page

### ISSUE THREAD

**Issue by alansam460** [alansam460/Skincare#11]
make html document for creating an account

**Comment by haiderratwit** [comment]
![create account 1](https://user-images.githubusercontent.com/57573664/158249381-c48e8921-8d94-47da-97ec-50971b4564b8.jpg)
![create account 2](https://user-images.githubusercontent.com/57573664/158249391-328adbc2-ce7f-48ab-81f6-eef54b6de361.jpg)
![manage account 1](https://user-images.githubusercontent.com/57573664/158249448-ed4a0455-0e28-499f-954d-c35f966d6099.jpg)
![manage account 2](https://user-images.githubusercontent.com/57573664/158249461-af17e23b-4f1a-4449-aee3-de17280eea3f.jpg)
