### ISSUE TITLE
Design quiz page

### ISSUE THREAD

**Issue by alansam460** [alansam460/Skincare#12]
Make html page for takign the quiz

**Comment by haiderratwit** [comment]
![take quiz 1](https://user-images.githubusercontent.com/57573664/158249884-57c31443-db27-4764-b510-313ad61bddbf.jpg)
![take quiz 2](https://user-images.githubusercontent.com/57573664/158249889-1274e246-a367-4253-a7e3-580394fb7f81.jpg)
![manage quiz 1](https://user-images.githubusercontent.com/57573664/158249900-070b0311-05eb-4d48-93ef-13e416636c3c.jpg)
![manage quiz 2](https://user-images.githubusercontent.com/57573664/158249906-98562e92-f545-4c24-a562-710c1defc9a5.jpg)
